---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.pelotech.ot
  resources:
  - datasyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.pelotech.ot
  resources:
  - datasyncs/finalizers
  verbs:
  - update
- apiGroups:
  - crd.pelotech.ot
  resources:
  - datasyncs/status
  verbs:
  - get
  - patch
  - update
