name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: install pre-commit
        run: pip install pre-commit

# TODO: add helm chart
#      - name: Build dependencies Helm - kic
#        uses: WyriHaximus/github-action-helm3@v4
#        with:
#          exec: helm dependency build charts/kic

      - name: pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
